export const ALL_SPELLS = [
  {
    id: 1,
    name: 'Abeyance',
    type: 'Magic Ball',
    school: 'Subdual',
    range: 'string',
    materials: 'Green Magic Ball',
    incantation: '"The strength of aether is mine to evoke" x3',
  },
  {
    id: 2,
    name: 'Adaptive Blessing',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee with this blessing" x3',
  },
  {
    id: 3,
    name: 'Adaptive Protection',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee with this protection" x3',
  },
  {
    id: 4,
    name: 'Adrenaline',
    type: 'Verbal',
    school: 'Spirit',
    range: 'Self',
    materials: 'string',
    incantation: '"Adrenaline"',
  },
  {
    id: 5,
    name: 'Amplification',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Touch',
    materials: 'Yellow Strip',
    incantation: '"My power amplifies thy voice" x3',
  },
  {
    id: 6,
    name: 'Ambulant',
    type: 'Meta-Magic',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: '"Ambulant"',
  },
  {
    id: 7,
    name: 'Ancestral Armor',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: `"May this armor protect thee from all forms of harm. May the flames of the fire not burn thee.
May the bolts from the heavens not strike thee.
May the arrows of your enemies not pierce thee. May this armor protect thee from all forms of harm."`,
  },
  {
    id: 8,
    name: 'Agoraphobia',
    type: 'Verbal',
    school: 'Command',
    range: "20'",
    materials: 'string',
    incantation: '"I command thee to be alone" x3',
  },
  {
    id: 9,
    name: 'Apex',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 10,
    name: 'Artificer',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 11,
    name: 'Assassinate',
    type: 'Verbal',
    school: 'Death',
    range: "50'",
    materials: 'string',
    incantation: '"Assassinate"',
  },
  {
    id: 12,
    name: 'Astral Intervention',
    type: 'string',
    school: 'string',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 13,
    name: 'Banish',
    type: 'Verbal',
    school: 'Spirit',
    range: "20'",
    materials: 'string',
    incantation: '"The spirits banish thee from this place" x3',
  },
  {
    id: 14,
    name: 'Barkskin',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee with barkskin" x3',
  },
  {
    id: 15,
    name: 'Battlefield Triage',
    type: 'Enchantment',
    school: 'Spirit',
    range: 'Touch',
    materials: 'string',
    incantation: '"Be a bastion of healing" x3',
  },
  {
    id: 16,
    name: 'Attuned',
    type: 'string',
    school: 'string',
    range: 'string',
    materials: 'Three yellow strips',
    incantation: 'string',
  },
  {
    id: 17,
    name: 'Battlemage',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 18,
    name: 'Bear Strength',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Other',
    materials: 'Red strip',
    incantation: '"I enchant thee with the strength of the bear" x3',
  },
  {
    id: 19,
    name: 'Avatar of Nature',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 20,
    name: 'Awe',
    type: 'Verbal',
    school: 'Command',
    range: "20'",
    materials: 'string',
    incantation: '"I command thee awed" x3',
  },
  {
    id: 21,
    name: 'Berserk',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Self',
    materials: 'Red strip',
    incantation: 'string',
  },
  {
    id: 22,
    name: 'Berserker',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
    {
    id: 23,
    name: 'Blessed Aura',
    type: 'Enchantment',
    school: 'Healing',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 24,
    name: 'Call Lightning',
    type: 'Verbal',
    school: 'Flame',
    range: "20'",
    materials: 'string',
    incantation: '"I call lightning\'s flame to strike thee" x3',
  },
  {
    id: 25,
    name: 'Blessing Against Harm',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee against all harm" x3',
  },
  {
    id: 26,
    name: 'Blessing Against Wounds',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee against wounds" x3',
  },
  {
    id: 27,
    name: 'Blink',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: '"I vanish from sight"',
  },
  {
    id: 28,
    name: 'Circle of Protection',
    type: 'Verbal',
    school: 'Protection',
    range: 'Touch',
    materials: 'string',
    incantation: '"Circle of Protection" x3',
  },
  {
    id: 29,
    name: 'Combat Caster',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 30,
    name: 'Blood and Thunder',
    type: 'Verbal',
    school: 'Spirit',
    range: 'Self',
    materials: 'string',
    incantation: '"Blood and Thunder!"',
  },
  {
    id: 31,
    name: 'Break Concentration',
    type: 'Verbal',
    school: 'Command',
    range: "20'",
    materials: 'string',
    incantation: '"I command thee suppressed"',
  },
  {
    id: 32,
    name: 'Brutal Strike',
    type: 'Verbal',
    school: 'Death',
    range: 'Unlimited',
    materials: 'string',
    incantation: '"And stay down!"',
  },
  {
    id: 33,
    name: 'Confidence',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Other',
    materials: 'string',
    incantation: '"My power grants thee confidence"',
  },
  {
    id: 34,
    name: 'Contagion',
    type: 'Enchantment',
    school: 'Death',
    range: 'Other',
    materials: 'Red strip',
    incantation: '"May thou bear this plague to all" x3',
  },
  {
    id: 35,
    name: 'Corrosive Mist',
    type: 'Enchantment',
    school: 'Death',
    range: 'Touch',
    materials: 'Three red strips',
    incantation: '"The mists of corrosion surround thee" x3',
  },
  {
    id: 36,
    name: 'Corruptor',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 37,
    name: 'Destruction Arrow',
    type: 'Specialty Arrow',
    school: 'Sorcery',
    range: 'string',
    materials: "Arrow with red head cover labeled 'Destruction'",
    incantation: '"Destruction Arrow"',
  },
  {
    id: 38,
    name: 'Dimensional Rift',
    type: 'Verbal',
    school: 'Neutral',
    range: 'Self',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 39,
    name: 'Coup de Grace',
    type: 'Verbal',
    school: 'Death',
    range: "20'",
    materials: 'string',
    incantation: '"Death shall come for thee" x3',
  },
  {
    id: 40,
    name: 'Dervish',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 41,
    name: 'Destroy Armor',
    type: 'Verbal',
    school: 'Death',
    range: "20'",
    materials: 'string',
    incantation: '"The power of the aether consumes thee" x3',
  },
  {
    id: 42,
    name: 'Discordia',
    type: 'Enchantment',
    school: 'Command',
    range: 'Self',
    materials: 'Five red strips',
    incantation: '"My discordant melodies shall stymie my foes" x3',
  },
  {
    id: 43,
    name: 'Dispel Magic',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"By my power I dispel that magic" x3',
  },
  {
    id: 44,
    name: 'Dragged Below',
    type: 'Verbal',
    school: 'Death',
    range: "20'",
    materials: 'string',
    incantation: '"Death comes for thee from below" x3',
  },
  {
    id: 45,
    name: 'Elemental Barrage',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: '"I am filled with the power of magic"',
  },
  {
    id: 46,
    name: 'Empower',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Other',
    materials: 'string',
    incantation: '"I empower thee"',
  },
  {
    id: 47,
    name: 'Enlightened Soul',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"A distant magic has no hold upon thy now enlightened soul" x3',
  },
  {
    id: 48,
    name: 'Entangle',
    type: 'Magic Ball',
    school: 'Subdual',
    range: 'string',
    materials: 'Brown Magic Ball',
    incantation: '"The strength of earth is mine to evoke" x3',
  },
  {
    id: 49,
    name: 'Equipment: Armor, 1 Point',
    type: 'Neutral',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 50,
    name: 'Equipment: Shield, Medium',
    type: 'Neutral',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 51,
    name: 'Equipment: Shield, Small',
    type: 'Neutral',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 52,
    name: 'Equipment: Weapon, Short',
    type: 'Neutral',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 53,
    name: 'Essence Graft',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Other',
    materials: 'Yellow strip',
    incantation: '"I enchant thee with essence graft" x3',
  },
  {
    id: 54,
    name: 'Evoker',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 55,
    name: 'Evolution',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 56,
    name: 'Experienced',
    type: 'Neutral',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 57,
    name: 'Extend Immunities',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"May the blessing of my god protect thee" x3',
  },
  {
    id: 58,
    name: 'Extension',
    type: 'Meta-Magic',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: '"Extension"',
  },
  {
    id: 59,
    name: 'Finger of Death',
    type: 'Verbal',
    school: 'Death',
    range: "20'",
    materials: 'string',
    incantation: '"I call upon death to smite thee" x3',
  },
  {
    id: 60,
    name: 'Fireball',
    type: 'Magic Ball',
    school: 'Flame',
    range: 'string',
    materials: 'Red Magic Ball',
    incantation: '"The flame of fire is mine to evoke" x3',
  },
  {
    id: 61,
    name: 'Force Bolt',
    type: 'Magic Ball',
    school: 'Sorcery',
    range: 'string',
    materials: 'Blue Magic Ball',
    incantation: '"Forcebolt" x3',
  },
  {
    id: 62,
    name: 'Gift of Air',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I grant thee a gift of the air" x3',
  },
  {
    id: 63,
    name: 'Gift of Earth',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I grant thee a gift of the earth" x3',
  },
  {
    id: 64,
    name: 'Gift of Fire',
    type: 'Enchantment',
    school: 'Flame',
    range: 'Other',
    materials: 'string',
    incantation: '"I grant thee a gift of the fire" x3',
  },
  {
    id: 65,
    name: 'Flame Blade',
    type: 'Enchantment',
    school: 'Flame',
    range: 'Other',
    materials: 'Red strip and white strip',
    incantation: '"The element of fire shall infuse your weapons" x3',
  },
  {
    id: 66,
    name: 'Force Barrier',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: '"I shall not be harmed"',
  },
  {
    id: 67,
    name: 'Gift of Water',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Other',
    materials: 'White strip and yellow strip',
    incantation: '"I grant thee a gift of the water" x3',
  },
  {
    id: 68,
    name: 'Golem',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Other',
    materials: 'White strip and yellow strip',
    incantation: '"From earth and clay I form thee" x3',
  },
  {
    id: 69,
    name: 'Greater Harden',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee with Greater Harden" x3',
  },
  {
    id: 70,
    name: 'Greater Heal',
    type: 'Verbal',
    school: 'Spirit',
    range: 'Touch',
    materials: 'string',
    incantation: '"By the grace of the divine thou art healed" x5',
  },
  {
    id: 71,
    name: 'Greater Mend',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Touch',
    materials: 'string',
    incantation: '"Return this <object name> to its former glory" x5',
  },
  {
    id: 72,
    name: 'Greater Resurrect',
    type: 'Verbal',
    school: 'Spirit',
    range: 'Other',
    materials: 'string',
    incantation: '"By the grace of the divine thou art resurrected" x5',
  },
  {
    id: 73,
    name: 'Guardian',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 74,
    name: 'Harden',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee with Harden" x3',
  },
  {
    id: 75,
    name: 'Heal',
    type: 'Verbal',
    school: 'Spirit',
    range: 'Touch',
    materials: 'string',
    incantation: '"The white light of healing hath healed thee." x5',
  },
  {
    id: 76,
    name: 'Greater Release',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"From all thine afflictions thou art released" x2',
  },
  {
    id: 77,
    name: 'Heart of the Swarm',
    type: 'Enchantment',
    school: 'Spirit',
    range: 'Self',
    materials: 'Yellow strip',
    incantation: '"Let all those who oppose the hive feel the wrath of the swarm" x3',
  },
  {
    id: 78,
    name: 'Heat Weapon',
    type: 'Verbal',
    school: 'Flame',
    range: "20'",
    materials: 'string',
    incantation: '"I call upon flame to heat that [type of weapon]" x3',
  },
  {
    id: 79,
    name: 'Hold Person',
    type: 'Verbal',
    school: 'Command',
    range: "20'",
    materials: 'string',
    incantation: '"I command thee to stop" x3',
  },
  {
    id: 80,
    name: 'Hunter',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 81,
    name: 'Imbue Shield',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"This Shield shall neither bend nor break" x3',
  },
  {
    id: 82,
    name: 'Iceball',
    type: 'Magic Ball',
    school: 'Subdual',
    range: 'string',
    materials: 'White Magic Ball',
    incantation: '"The strength of ice is mine to evoke" x3',
  },
  {
    id: 83,
    name: 'Icy Blast',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"My power makes thee frozen" x3',
  },
  {
    id: 84,
    name: 'Imbue Armor',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee with Imbued Armor" x3',
  },
  {
    id: 85,
    name: 'Infernal',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 86,
    name: 'Innate',
    type: 'Meta-Magic',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: '"Innate"',
  },
  {
    id: 87,
    name: 'Inquisitor',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 88,
    name: 'Insult',
    type: 'Verbal',
    school: 'Command',
    range: "20'",
    materials: 'string',
    incantation: '"I command thy attention" x3',
  },
  {
    id: 89,
    name: 'Ironskin',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee with Ironskin" x3',
  },
  {
    id: 90,
    name: 'Juggernaut',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 91,
    name: 'Legend',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 92,
    name: 'Lightning Bolt',
    type: 'Magic Ball',
    school: 'Flame',
    range: 'string',
    materials: 'Yellow Magic Ball',
    incantation: '"The flame of storms is mine to evoke" x3',
  },
  {
    id: 93,
    name: 'Lost',
    type: 'Verbal',
    school: 'Command',
    range: "20'",
    materials: 'string',
    incantation: '"I command thee to be lost" x3',
  },
  {
    id: 94,
    name: 'Lycanthropy',
    type: 'Enchantment',
    school: 'Death',
    range: 'Other',
    materials: 'White strip and red strip',
    incantation: '"I enchant thee with Lycanthropy" x3',
  },
  {
    id: 95,
    name: 'Martyr',
    type: 'Verbal',
    school: 'Spirit',
    range: 'Other',
    materials: 'string',
    incantation: '"Thy burdens are mine to bear."',
  },
  {
    id: 96,
    name: 'Mass Healing',
    type: 'Enchantment',
    school: 'Spirit',
    range: 'Self',
    materials: 'Five yellow strips',
    incantation: '"Let the powers of healing flow through me" x3',
  },
  {
    id: 97,
    name: 'Medium',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 98,
    name: 'Mend',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Touch',
    materials: 'string',
    incantation: '"I make this item whole again" x5',
  },
  {
    id: 99,
    name: 'Missile Block',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 100,
    name: 'Momentum',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: '"Momentum"',
  },
    {
    id: 101,
    name: 'Mutation',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 102,
    name: 'Mystic',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 103,
    name: 'Naturalize Magic',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Self',
    materials: 'Three red strips',
    incantation: '"I shall restore the balance" x3',
  },
  {
    id: 104,
    name: 'Necromancer',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 105,
    name: 'Persistent',
    type: 'Meta-Magic',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: '"Persistent"',
  },
  {
    id: 106,
    name: 'Phase Arrow',
    type: 'Specialty Arrow',
    school: 'Sorcery',
    range: 'string',
    materials: "Arrow with gray cover labeled 'Phase'",
    incantation: '"Phase Arrow"',
  },
  {
    id: 107,
    name: 'Phase Bolt',
    type: 'Magic Ball',
    school: 'Sorcery',
    range: 'string',
    materials: 'Gray Magic Ball',
    incantation: '"The power of sorcery is mine to evoke" x3',
  },
  {
    id: 108,
    name: 'Phoenix Tears',
    type: 'Enchantment',
    school: 'Spirit',
    range: 'Other',
    materials: 'Two white strips',
    incantation: '"May the tears of the phoenix wash over thee" x3',
  },
  {
    id: 109,
    name: 'Pinning Arrow',
    type: 'Specialty Arrow',
    school: 'Sorcery',
    range: 'string',
    materials: "Arrow with yellow head cover labeled 'Pinning'",
    incantation: '"Pinning Arrow"',
  },
  {
    id: 110,
    name: 'Planar Grounding',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"My power closes the aether to you" x3',
  },
  {
    id: 111,
    name: 'Poison',
    type: 'Enchantment',
    school: 'Death',
    range: 'Self',
    materials: 'Red strip',
    incantation: '"I coat these weapons with a deadly poison" x2',
  },
  {
    id: 112,
    name: 'Poison Arrow',
    type: 'Specialty Arrow',
    school: 'Death',
    range: 'string',
    materials: "Arrow with green head cover labeled 'Poison'",
    incantation: '"Poison Arrow"',
  },
  {
    id: 113,
    name: 'Poison Glands',
    type: 'Enchantment',
    school: 'Death',
    range: 'Other',
    materials: 'Red strip',
    incantation: '"Thou shalt secrete poison from thy venemous glands" x3',
  },
  {
    id: 114,
    name: 'Priest',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 115,
    name: 'Pyrotechnics',
    type: 'Verbal',
    school: 'Flame',
    range: "50'",
    materials: 'string',
    incantation: '"I call upon the element of flame to destroy thy belongings" x3',
  },
  {
    id: 116,
    name: 'Rage',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: '"I am filled with rage!"',
  },
  {
    id: 117,
    name: 'Raider',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 118,
    name: 'Protection from Magic',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee with protection from magic" x3',
  },
  {
    id: 119,
    name: 'Protection from Projectiles',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"I enchant thee with Protection from Projectiles" x3',
  },
  {
    id: 120,
    name: 'Raise Dead',
    type: 'Verbal',
    school: 'Death',
    range: 'Touch',
    materials: 'string',
    incantation: '"Rise and fight again" x5',
  },
  {
    id: 121,
    name: 'Ranger',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 122,
    name: 'Ravage',
    type: 'Verbal',
    school: 'Death',
    range: "20'",
    materials: 'string',
    incantation: '"Death shall make thee fragile" x3',
  },
  {
    id: 123,
    name: 'Regeneration',
    type: 'Enchantment',
    school: 'Spirit',
    range: 'Other',
    materials: 'Yellow strip',
    incantation: '"I grant thee the power of regeneration" x3',
  },
  {
    id: 124,
    name: 'Release',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Touch',
    materials: 'string',
    incantation: '"From thy bindings thou art released" x5',
  },
  {
    id: 125,
    name: 'Reload',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: '"I nocked my arrows to my bow, I let them fly, my quiver is low. Now I pause to go reload." x3',
  },
  {
    id: 126,
    name: 'Restoration',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Other',
    materials: 'string',
    incantation: '"I restore thee to thy full potency"',
  },
  {
    id: 127,
    name: 'Resurrect',
    type: 'Verbal',
    school: 'Spirit',
    range: 'Other',
    materials: 'string',
    incantation: `"Sword Cut, spear stab, mace smash, arrow jab, Let the white light of healing descend on thee. Let the white light of healing stop thy spilling blood. Let the white light of healing mend thy bones. Let the white light of healing close thy wounds. Let the white light of healing restore thy vigor. The white light of healing hath resurrected thee."`,
  },
  {
    id: 128,
    name: 'Sanctuary',
    type: 'Verbal',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"Sanctuary"',
  },
  {
    id: 129,
    name: 'Scavenge',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: '"Scavenge"',
  },
  {
    id: 130,
    name: 'Sever Spirit',
    type: 'Verbal',
    school: 'Spirit',
    range: "20'",
    materials: 'string',
    incantation: '"The spirits lay a curse on thee." x3',
  },
  {
    id: 131,
    name: 'Shadow Step',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Self',
    materials: 'string',
    incantation: '"I step into the shadows"',
  },
  {
    id: 132,
    name: 'Shake It Off',
    type: 'Verbal',
    school: 'Spirit',
    range: 'Self',
    materials: 'string',
    incantation: '"I shall overcome"',
  },
  {
    id: 133,
    name: 'Shatter',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"My power shatters thy body" x3',
  },
  {
    id: 134,
    name: 'Shove',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"My power shoves thee" x3',
  },
  {
    id: 135,
    name: 'Silver Tongue',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Touch',
    materials: 'Yellow strip',
    incantation: '"My power quickens thine" x3',
  },
  {
    id: 136,
    name: 'Sleight of Mind',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Other',
    materials: 'Yellow strip',
    incantation: '"May thy power remain" x3',
  },
  {
    id: 137,
    name: 'Snaring Vines',
    type: 'Enchantment',
    school: 'Command',
    range: 'Self',
    materials: 'Three red strips',
    incantation: '"The hands of the earth rise to your bidding" x3',
  },
  {
    id: 138,
    name: 'Shatter Weapon',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"My power destroys thy [type of weapon]" x3',
  },
  {
    id: 139,
    name: 'Sniper',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 140,
    name: 'Song of Battle',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"I sing of my legendary prowess"',
  },
  {
    id: 141,
    name: 'Song of Deflection',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"I sing of my nimble acrobatics"',
  },
  {
    id: 142,
    name: 'Song of Determination',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"I sing of my unwavering determination"',
  },
  {
    id: 143,
    name: 'Song of Freedom',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"I sing of my unquenchable wanderlust"',
  },
  {
    id: 144,
    name: 'Song of Interference',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"I sing a song of dark magic thwarted"',
  },
  {
    id: 145,
    name: 'Song of Power',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"I sing to inspire my comrades-in-arms"',
  },
  {
    id: 146,
    name: 'Song of Survival',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"I sing of my numerous close calls"',
  },
  {
    id: 147,
    name: 'Song of Visit',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"I sing to entertain friend and foe" x3',
  },
  {
    id: 148,
    name: 'Stun',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"By the power of white light I stun thee" x3',
  },
  {
    id: 149,
    name: 'Sphere of Annihilation',
    type: 'Magic Ball',
    school: 'Sorcery',
    range: 'string',
    materials: 'Black Magic Ball',
    incantation: '"The power of void is mine to evoke" x3',
  },
  {
    id: 150,
    name: 'Spy',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 151,
    name: 'Steal Life Essence',
    type: 'Verbal',
    school: 'Death',
    range: 'Touch',
    materials: 'string',
    incantation: '"Steal life"',
  },
  {
    id: 152,
    name: 'Stoneform',
    type: 'Verbal',
    school: 'Protection',
    range: 'Self',
    materials: 'string',
    incantation: '"I take the form of stone"',
  },
  {
    id: 153,
    name: 'Stoneskin',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'White strip',
    incantation: '"May nature protect thee from all forms of attack" x3',
  },
  {
    id: 154,
    name: 'Summon Dead',
    type: 'Verbal',
    school: 'Spirit',
    range: "50'",
    materials: 'string',
    incantation: '"I summon thy corpse" x5',
  },
  {
    id: 155,
    name: 'Summoner',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 156,
    name: 'Suppress Aura',
    type: 'Verbal',
    school: 'Command',
    range: "50'",
    materials: 'string',
    incantation: '"I command thee powerless" x3',
  },
  {
    id: 157,
    name: 'Suppression Arrow',
    type: 'Specialty Arrow',
    school: 'Sorcery',
    range: 'string',
    materials: "Arrow with purple head cover labeled 'Suppression'",
    incantation: '"Suppression Arrow"',
  },
  {
    id: 158,
    name: 'Suppression Bolt',
    type: 'Magic Ball',
    school: 'Subdual',
    range: 'string',
    materials: 'Purple Magic Ball',
    incantation: '"The strength of suppression is mine to evoke" x3',
  },
  {
    id: 159,
    name: 'Swift',
    type: 'Meta-Magic',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: '"Swift"',
  },
  {
    id: 160,
    name: 'Teleport',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"I travel through the aether" x5',
  },
    {
    id: 161,
    name: 'Terror',
    type: 'Verbal',
    school: 'Death',
    range: "20'",
    materials: 'string',
    incantation: '"Death makes thee terrified" x3',
  },
  {
    id: 162,
    name: 'Throw',
    type: 'Verbal',
    school: 'Death',
    range: "20'",
    materials: 'string',
    incantation: '"My power throws thee" x3',
  },
  {
    id: 163,
    name: 'Tracking',
    type: 'Verbal',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: '"Tracking" x3',
  },
  {
    id: 164,
    name: 'Trickery',
    type: 'Enchantment',
    school: 'Sorcery',
    range: "20'",
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 165,
    name: 'Troll Blood',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Other',
    materials: 'string',
    incantation: '"The blood of the trolls sustains thee" x3',
  },
  {
    id: 166,
    name: 'True Grit',
    type: 'Verbal',
    school: 'Spirit',
    range: 'Self',
    materials: 'string',
    incantation: '"The wicked flee when I pursue"',
  },
  {
    id: 167,
    name: 'Undead Minion',
    type: 'Enchantment',
    school: 'Death',
    range: 'Other',
    materials: 'Yellow strip',
    incantation: `
    "Flesh rots, bones break, skulls sigh, spirits take, 
    let the power of my will descend on thee
    let the power of my will restore thy spirit
    let the power of my will knit thy corpse
    let the power of my will give thee direction
    let the power of my will cheat thy death
    by the power of my will, arise my minion!"`,
  },
  {
    id: 168,
    name: 'Vampirism',
    type: 'Enchantment',
    school: 'Death',
    range: 'Other',
    materials: 'Yellow and white strip',
    incantation: '"Thy hunger can never be sated" x3',
  },
  {
    id: 169,
    name: 'Void Touched',
    type: 'Enchantment',
    school: 'Sorcery',
    range: 'Other',
    materials: 'Red and white strip',
    incantation: '"Embrace the old ones and surrender thyself" x3',
  },
  {
    id: 170,
    name: 'Ward Self',
    type: 'Enchantment',
    school: 'Protection',
    range: 'Self',
    materials: 'White strip',
    incantation: '"The power of magic defends me" x3',
  },
  {
    id: 171,
    name: 'Warder',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 172,
    name: 'Warlock',
    type: 'Archetype',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
  {
    id: 173,
    name: 'Word of Mending',
    type: 'Verbal',
    school: 'Sorcery',
    range: 'Touch',
    materials: 'string',
    incantation: 'Spedoinkle',
  },
  {
    id: 174,
    name: 'Wounding',
    type: 'Verbal',
    school: 'Death',
    range: "20'",
    materials: 'string',
    incantation: '"Death strikes off why [left/right] [arm/leg]" x3',
  },
  {
    id: 175,
    name: 'EquipmentL Weapon, Long',
    type: 'Neutral',
    school: 'Neutral',
    range: 'string',
    materials: 'string',
    incantation: 'string',
  },
]

export const BARD_SPELLS = [
  {
    level: 1,
    spells: [
      { id: 33, cost: 1, max: null, frequency: '1/Refresh Charge x5'},
      { id: 52, cost: 2, max: 2, frequency: null},
      { id: 56, cost: 2, max: 2, frequency: null},
      { id: 88, cost: 1, max: null, frequency: '1/Life'},
      { id: 124, cost: 1, max: null, frequency: '1/Life'},
      { id: 134, cost: 1, max: null, frequency: '1/Life'},
      { id: 142, cost: 1, max: 1, frequency: 'Unlimited'},
    ]
  },
  {
    level: 2,
    spells: [
      { id: 46, cost: 1, max: null, frequency: '2/Refresh'},
      { id: 49, cost: 3, max: 1, frequency: null},
      { id: 76, cost: 2, max: null, frequency: '1/Refresh'},
      { id: 86, cost: 1, max: 4, frequency: '1/Refresh'},
      { id: 98, cost: 1, max: null, frequency: '1/Life'},
      { id: 140, cost: 1, max: 1, frequency: 'Unlimited'},
      { id: 147, cost: 1, max: 1, frequency: 'Unlimited'},
    ]
  },
  {
    level: 3,
    spells: [
      { id: 20, cost: 1, max: null, frequency: '1/Life'},
      { id: 15, cost: 1, max: 1, frequency: '1/Refresh'},
      { id: 31, cost: 1, max: 4, frequency: '1/Life'},
      { id: 58, cost: 1, max: 2, frequency: '1/Life'},
      { id: 51, cost: 2, max: 1, frequency: null},
      { id: 143, cost: 1, max: 1, frequency: 'Unlimited'},
    ]
  },
  {
    level: 4,
    spells: [
      { id: 5, cost: 1, max: 4, frequency: '1/Life'},
      { id: 175, cost: 3, max: 1, frequency: null},
      { id: 126, cost: 1, max: null, frequency: '1/Refresh'},
      { id: 136, cost: 1, max: null, frequency: '1/Refresh'},
      { id: 141, cost: 1, max: 1, frequency: 'Unlimited'},
      { id: 145, cost: 1, max: 1, frequency: 'Unlimited'},
      { id: 156, cost: 1, max: null, frequency: '1/Refresh'},
      { id: 159, cost: 1, max: 2, frequency: '1/Life'},
      { id: 161, cost: 1, max: null, frequency: '1/Refresh'},
    ]
  },
  {
    level: 5,
    spells: [
      { id: 8, cost: 1, max: null, frequency: '1/Refresh'},
      { id: 6, cost: 1, max: 2, frequency: '1/Life'},
      { id: 42, cost: 1, max: 1, frequency: '1/Refresh'},
      { id: 50, cost: 3, max: 1, frequency: null},
      { id: 77, cost: 1, max: null, frequency: '1/Refresh'},
      { id: 93, cost: 1, max: null, frequency: '1/Life'},
      { id: 146, cost: 1, max: 1, frequency: 'Unlimited'},
    ]
  },
  {
    level: 6,
    spells: [
      { id: 29, cost: 2, max: 1, frequency: null},
      { id: 40, cost: 2, max: 1, frequency: null},
      { id: 49, cost: 2, max: 1, frequency: null},
      { id: 91, cost: 1, max: 1, frequency: null},
      { id: 135, cost: 1, max: null, frequency: '1/Refresh'},
      { id: 144, cost: 1, max: 1, frequency: '1/Refresh Charge x5'},
      { id: 148, cost: 1, max: null, frequency: '1/Refresh'},
    ]
  },
]